### ISSUE TITLE
Clarify that "supportsaudioprocessing" must be present in project.json for Audio Visualization to work.

### ISSUE THREAD

**Issue by akett** [Wallpaper-Engine-Team/wallpaper-engine-docs#1]
The guide for Audio Visualization in the web docs will not work if the user does not have the "supportsaudioprocessing" flag set in their project.json.

Since the Editor doesn't automatically add this flag for new web projects, I think it should be clarified that the flag is a requirement.

I was able to figure it out by searching the web and finding the "old" guides on Steam, but it would be nice if that information was available in the official docs.

Here is an excerpt from the old Steam guide ----

## Enable audio input on your wallpaper

Before Wallpaper Engine will send you any audio data, you will have to set a flag in the project.json file of your wallpaper. So make sure to import your wallpaper in the editor first and then open the project.json from the wallpaper directory. The flag you need to set is named 'supportsaudioprocessing' and it's a member of the 'general' object. Simply setting this flag to true will suffice, as the following sample demonstrates:

```
{
    "file" : "index.html",
    "preview" : "prev.png",
    "general" : 
    {
        "supportsaudioprocessing" : true
    },
    "title" : "Advanced Web Tutorial - Audio Input",
    "type" : "web"
}
```

**Comment by TiEul** [comment]
Hey @akett, the editor adds this flag automatically, users don't need to manually edit the project.json file anymore, the Steam guide you found is extremely outdated and back then this was necessary. If you continue to have this issue, please post on the Steam forums or send us an email, we'll gladly check this out more though this Github repo isn't the right place for tech support with the app:

https://steamcommunity.com/app/431960/discussions/1/

Thanks!
